name: gh-pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Build Storybook
        run: nix develop --command bash -c "npm i --legacy-peer-deps && npm run build-storybook"
      - name: Build Test Coverage
        run: nix develop --command bash -c "npm i --legacy-peer-deps && npm run coverage"
      - name: Move Coverage Report
        run: |
          mv ./coverage/ ./storybook-static/coverage 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
